import type { ImageId } from '../media'

/**
 * Spreadsheet Agent (brief v17): the page is built around review and
 * traceability. Hero and scope, the problem, a four-stage demonstration,
 * two design decisions with their tradeoff, and what the prototype
 * demonstrates beside its limitations.
 *
 * The demonstration was captured on 2026-09-25 from the live prototype
 * (spreadsheetagent.netlify.app, the build in the September recording) with
 * a request its plan answers exactly: “Create a sheet of B2B products with
 * vendor, cost, retail price, and margin.” The plan lists the Northwind
 * product catalog (1,200 synthetic records), no filters, the columns SKU,
 * Product Name, Vendor, Cost, Retail Price and Margin Percent, sorted by
 * product name; the built sheet has 1,200 rows and six columns; selecting
 * Atlas Goods (C3) and opening Detail shows the field
 * northwind.catalog.products[].vendor.name, the dataset Northwind Goods
 * product catalog v1.0.0, record B2B-1595, its definition and why the
 * column was chosen. The earlier recording's request (“Compare vendor
 * prices…”) is no longer shown: its plan performed no comparison.
 *
 * Scope, stated once beside the demonstration: working prototype, synthetic
 * catalog, rule-based responses (a deterministic rule engine, no model).
 */
export const SHEET = {
  title: 'Spreadsheet Agent',
  meta: ['Independent project', 'Product design and build', '2026'],
  summary: (
    <p>
      I built a prototype spreadsheet agent that turns a written request into a structured, editable sheet. It adds matching rows from a product catalog and
      shows a plan to review before it builds anything.
    </p>
  ),
  hero: 'sa-cover' as ImageId,

  problem: {
    heading: 'Review the plan before the sheet is built.',
    body: 'A written request can be read more than one way. The same words might point to a different source, other columns, or another order, and a sheet built on the wrong reading looks just as finished as a right one. So the agent first shows its plan, naming the source, columns, filters, and sort, and lists any words it could not use.',
  },

  demo: {
    scope: 'Working prototype · Synthetic catalog · Rule-based responses',
    scopeNote: 'The agent’s responses come from a set of rules written for this prototype; they are simulated, not generated by a live model.',
    request: 'Create a sheet of B2B products with vendor, cost, retail price, and margin.',
    stages: [
      { label: 'Request', image: 'sa-stage-request' as ImageId, caption: 'An empty sheet and the request, written in plain language in the assistant panel.' },
      {
        label: 'Review plan',
        image: 'sa-stage-plan' as ImageId,
        caption: 'The plan names the source, filters, the six columns, the sort, and the row limit, and waits for review.',
      },
      { label: 'Build sheet', image: 'sa-stage-sheet' as ImageId, caption: 'Building fills 1,200 rows and six columns, and the reply confirms what was built.' },
      { label: 'Trace a value', caption: 'Inspect the catalog field behind a selected value.' },
    ],
  },

  decisions: {
    heading: 'Design decisions',
    items: [
      {
        title: 'Show the plan instead of a spinner',
        body: 'The interpreter is a set of rules, not a model, so rather than hide it, the prototype shows exactly what it will build and waits for a decision.',
      },
      {
        title: 'Keep every value traceable',
        body: 'Any cell can be selected to see the dataset, record, and field behind it, with the reason its column was included.',
      },
    ],
    tradeoff: {
      title: 'The tradeoff',
      body: 'Rules are predictable and easy to inspect, but narrow. A request outside their vocabulary is met with unused words listed in the plan, not a guess.',
    },
  },

  closing: {
    lead: 'A reviewable plan becomes an editable sheet.',
    meta: '1,200 synthetic rows · 6 columns · 1 review step',
    demonstrated: [
      { title: 'Plan review', text: 'Source, columns, filters, and sort are shown and confirmed before building.' },
      { title: 'Sheet creation', text: 'One confirmed plan becomes a saved, titled sheet.' },
      { title: 'Source inspection', text: 'A selected value opens the catalog field and record behind it.' },
    ],
    limitations: [
      'The responses are rule-based; no language model is involved.',
      'The catalog is synthetic, so real data quality and scale are untested.',
      'The walkthrough does not show an edit to the finished sheet.',
      'How well the review step works for the people who build these sheets remains to be validated.',
    ],
  },
}
